
ascii:
data '       X  XX XX X X   X      X       X     X  X   X   X                        X XXX   X   XXX XXXX    X XXXXX   X XXXXX XXX  XXX                           XXX  XXX  XXX XXXX  XXXXXXXX XXXXXXXXXXXXXXXX   XXXXXXXXXXXX   XX    X   XX   X XXX XXXX  XXX XXXX XXXXXXXXXXX   XX   XX   XX   XX   XXXXXX XXX X     XXX   X                                                                                                                                            XX  X  XX        '
data '      XXX XX XX X X XXXXX X  X X     X    X    X   XXX                        XXX  XX XX  X   X    X  XX X      X      XX   XX   X  XX   XX    XX     XX   X   XX   XX   XX   XX    X   XX    X    X    X   X  X    X  X  X X    XX XXXX  XX   XX   XX   XX   XX      X  X   XX   XX   XX   XX   X    X X   XX      X  X X           X             X       XXX     X      X     X X    XXX                                      X                                   X    X    X       '
data '       X   X X XXXXXX X     X X X    X   X      X XXXXX  X                   XX X X XX X     XX    X X X X     X       XX   XX   X  XX   XX  XX  XXXXX  XX     XX XXXX   XX   XX    X   XX    X    X    X   X  X    X  X X  X    X X XXX  XX   XX   XX   XX   XX      X  X   XX   XX   X X X  X X    X  X    XX     X X   X      XXX X     XXXX    X XXX  X    XXXXX              X      X   X X  XXX  XXX XXXX  XXXXX XXX XXXXXXXXXX   XX   XX   XX   XX   XXXXXX  X    X    X   X  X'
data '       X        X X XXXXX  X   X         X      X  XXX   X                   X  X X X  X   XX   XXX XXXXXXXXX XXXX    X  XXX  XXX           X             X   X X X XXXXXXX  X X    X   XXXX  XXX  X  XXXXXXX  X    X  XX   X    X X XX X XX   XXXXX X   XXXXX  XXX   X  X   X X X X X X  X    X    X   X     X     X               XXXXX X     XXXXX   XXXXXXX   XX    XXX  XXXX X XX   X  X X X X  XX   XX   XX   XXX   X     X   X   XX   XX   X X X X  X    X XX           XXX X X'
data '       X       XXXXX  X X X   X X X      X      X X   XXXXXX  XX XXXXX  XX  XX  X X X  X  X        X   X     XX   X  X  X   X    X  XX   XX  XX  XXXXX  XX   X  X XX X   XX   XX    X   XX    X    X   XX   X  X    X  X X  X    X   XX  XXX   XX    X   XX   X    X  X  X   X X X X X X X X   X   X    X     XX    X            XXXXX   XX    X   XXXXXX X    XXXXXXXX   X     X XX     X  X X X X  XX   XX   XX   XX     XXX  X   X   XX   XX X X  X    X    X    X    X    X  X  X '
data '                X X XXXXXX  X X  X        X    X         X    XX        XX XX   XX  X  X  X        X   X     XX   X X   X   X    X  XX   XX    XX     XX        X    X   XX   XX    X   XX    X    X   XX   X  X    X  X  X X    X   XX  XXX   XX     XXX X   X    X  X  X   X X X XX XXX   X  X  X     X      XX   X           X   XX   XX    X   XX     X       XX   X  X     X X X    X  X X X X  XX   XXXXX  XXXXX        X X   X   X X X X X X X X  X    X     X    X    X       '
data '       X        X X   X  X     XX X        X  X          X   XX            X     XXX XXXXXXXXXXXXXX    X XXXX  XXX X     XXX  XXX       XX                   X   XXXXX   XXXXX  XXXXXXXX XXXXXX    XXXXXX   XXXXXXXXX  X   XXXXXXX   XX   X XXX X       XXX   XXXXXX  X   XXX   X  X   XX   X  X  XXXXX XXX     X XXX      XXXXX XXXXXXXX  XXXX XXXX XXX  X   XXXX X   X   X XXX  X  X    X X X X X  X XXX X        XX    XXXX   XXX XXX   X   X X X   XX    XXXXX   XX  X  XX        '
